[project]
name = "asteca"
version = "0.5.9"
description = "Stellar cluster analysis package"
authors = [
    {name = "Gabriel I Perren", email = "gabrielperren@gmail.com"}
]
readme = "README.md"
license = "MIT"
keywords = ["cluster", "astrophysics"]
homepage = "https://asteca.github.io/"
repository = "https://github.com/asteca/ASteCA"
documentation = "https://asteca.readthedocs.io/"
requires-python = ">=3.12"
dependencies = ["numpy (>=2.2.1,<3.0.0)", "matplotlib (>=3.10.0,<4.0.0)", "scipy (>=1.15.0,<2.0.0)", "astropy (>=7.0.0,<8.0.0)", "pandas (>=2.2.3,<3.0.0)", "fast-histogram (>=0.14,<0.15)"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
